spring.application.name=TennoSquad
server.port=8092

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tenno_squad
spring.datasource.username=postgres
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Default profile
spring.profiles.default=default


#Base
warframe.api.base-url=https://api.warframestat.us