spring.application.name=TennoSquad
server.port=8093


# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/tenno_squad_dev
spring.datasource.username=postgres
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


#base
warframe.api.base-url=https://api.warframestat.us